import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import dashboardRouter from "./dashboard";
import donationsRouter from "./donations";
import expensesRouter from "./expenses";
import fundsRouter from "./funds";
import accountsRouter from "./accounts";
import vendorsRouter from "./vendors";
import billsRouter from "./bills";
import pledgesRouter from "./pledges";
import journalEntriesRouter from "./journal-entries";
import bankAccountsRouter from "./bank-accounts";
import bankTransactionsRouter from "./bank-transactions";
import reportsRouter from "./reports";
import companiesRouter from "./companies";
import usersRouter from "./users";
import budgetsRouter from "./budgets";
import reconciliationRouter from "./reconciliation";
import chartOfAccountsRouter from "./chart-of-accounts";
import transactionsRouter from "./transactions";
import openingBalanceRouter from "./opening-balance";
import trialBalanceRouter from "./trial-balance";
import periodCloseRouter from "./period-close";
import masterAdminRouter from "./master-admin";
import helpMessagesRouter from "./help-messages";
import stripeRouter from "./stripe";
import plaidRouter from "./plaid";
import financialSummaryRouter from "./financial-summary";

const router: IRouter = Router();

router.use("/healthz", healthRouter);
router.use("/auth", authRouter);
router.use("/dashboard", dashboardRouter);
router.use("/donations", donationsRouter);
router.use("/expenses", expensesRouter);
router.use("/funds", fundsRouter);
router.use("/accounts", accountsRouter);
router.use("/vendors", vendorsRouter);
router.use("/bills", billsRouter);
router.use("/pledges", pledgesRouter);
router.use("/journal-entries", journalEntriesRouter);
router.use("/bank-accounts", bankAccountsRouter);
router.use("/bank-transactions", bankTransactionsRouter);
router.use("/reports", reportsRouter);
router.use("/companies", companiesRouter);
router.use("/users", usersRouter);
router.use("/budgets", budgetsRouter);
router.use("/reconciliation", reconciliationRouter);
router.use("/chart-of-accounts", chartOfAccountsRouter);
router.use("/transactions", transactionsRouter);
router.use("/opening-balance", openingBalanceRouter);
router.use("/trial-balance", trialBalanceRouter);
router.use("/period-close", periodCloseRouter);
router.use("/master-admin", masterAdminRouter);
router.use("/help-messages", helpMessagesRouter);
router.use("/stripe", stripeRouter);
router.use("/plaid", plaidRouter);
router.use("/financial-summary", financialSummaryRouter);

export default router;
